//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sadovDiplomaDOMEntities : DbContext
    {
        public sadovDiplomaDOMEntities()
            : base("name=sadovDiplomaDOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<DepartmentAccounts> DepartmentAccounts { get; set; }
        public DbSet<Departments> Departments { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Hypermarkets> Hypermarkets { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ReasonsRequests> ReasonsRequests { get; set; }
        public DbSet<RemaindProducts> RemaindProducts { get; set; }
        public DbSet<RequestsMarking> RequestsMarking { get; set; }
        public DbSet<RequestsWriteOff> RequestsWriteOff { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<StatusesRequestsMarking> StatusesRequestsMarking { get; set; }
        public DbSet<StatusesRequestsWriteOff> StatusesRequestsWriteOff { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
