//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentAccounts
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public string localPhone { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> hypermarketId { get; set; }
    
        public virtual Hypermarkets Hypermarkets { get; set; }
    }
}
