//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.RequestsMarking = new HashSet<RequestsMarking>();
            this.RequestsWriteOff = new HashSet<RequestsWriteOff>();
            this.RequestsWriteOff1 = new HashSet<RequestsWriteOff>();
        }
        public string FullName
        {
            get { return $"{surname} {name} {patronymic}"; }
            set { }
        }
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> hypermarketId { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual Hypermarkets Hypermarkets { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<RequestsMarking> RequestsMarking { get; set; }
        public virtual ICollection<RequestsWriteOff> RequestsWriteOff { get; set; }
        public virtual ICollection<RequestsWriteOff> RequestsWriteOff1 { get; set; }
    }
}
