//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hypermarkets
    {
        public Hypermarkets()
        {
            this.DepartmentAccounts = new HashSet<DepartmentAccounts>();
            this.Employees = new HashSet<Employees>();
            this.RemaindProducts = new HashSet<RemaindProducts>();
        }
    
        public int id { get; set; }
        public string branchName { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
    
        public virtual ICollection<DepartmentAccounts> DepartmentAccounts { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<RemaindProducts> RemaindProducts { get; set; }
    }
}
