//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Products
    {
        public Products()
        {
            this.RemaindProducts = new HashSet<RemaindProducts>();
            this.RequestsMarking = new HashSet<RequestsMarking>();
            this.RequestsWriteOff = new HashSet<RequestsWriteOff>();
        }

        public string imagePath
        {
            get
            {
                if (image == "" || image == null || !File.Exists(Directory.GetCurrentDirectory() + "\\ImagesProducts\\" + image))
                {
                    return Directory.GetCurrentDirectory() + "\\ImagesProducts\\" + "void.png";
                }
                else
                {
                    return Directory.GetCurrentDirectory() + "\\ImagesProducts\\" + image;
                }
            }
            set { }
        }
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string image { get; set; }
        public string size { get; set; }
        public Nullable<double> weight { get; set; }
        public string color { get; set; }
        public Nullable<double> purchasePrice { get; set; }
        public Nullable<double> salePrice { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<RemaindProducts> RemaindProducts { get; set; }
        public virtual ICollection<RequestsMarking> RequestsMarking { get; set; }
        public virtual ICollection<RequestsWriteOff> RequestsWriteOff { get; set; }
    }
}
