//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class RequestsMarking
    {
        public SolidColorBrush ColorStatus
        {
            get
            {
                switch (StatusesRequestsMarking.name)
                {
                    case "Создана":
                        {
                            return Brushes.LightGreen;
                        }
                    case "В работе":
                        {
                            return Brushes.LightBlue;
                        }
                    case "Закрыта":
                        {
                            return Brushes.IndianRed;
                        }
                    default:
                        {
                            return Brushes.White;
                        }
                }
            }
            set { }
        }
        public int id { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> reasonId { get; set; }
        public Nullable<int> creatorId { get; set; }
        public string actionsTaken { get; set; }
        public Nullable<int> statusId { get; set; }
        public string executor { get; set; }
        public string description { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
        public virtual ReasonsRequests ReasonsRequests { get; set; }
        public virtual StatusesRequestsMarking StatusesRequestsMarking { get; set; }
    }
}
