//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows;
    using System.Windows.Media;

    public partial class RequestsWriteOff
    {
        public SolidColorBrush ColorStatus
        {
            get
            {
                switch (StatusesRequestsWriteOff.name)
                {
                    case "Создана":
                        {
                            return Brushes.LightGreen;
                        }
                    case "Проверка товара":
                        {
                            return Brushes.LightBlue;
                        }
                    case "Товар на складе брака":
                        {
                            return Brushes.IndianRed;
                        }
                    default:
                        {
                            return Brushes.White;
                        }
                }
            }
            set { }
        }

        public string SummWriteOff
        {
            get
            {
                if (StatusesRequestsWriteOff.name == "Товар на складе брака")
                {
                    return $@"{Products.purchasePrice * quantity} руб.";
                }
                else
                {
                    return "";
                }
            }
            set { }
        }

        public Visibility VisibilitySummWriteOff
        {
            get
            {
                if (StatusesRequestsWriteOff.name == "Товар на складе брака")
                {
                    return Visibility.Visible;
                }
                else
                {
                    return Visibility.Collapsed;
                }
            }
            set { }
        }
        public int id { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> creatorId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> storekeeperId { get; set; }
        public string desciption { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Products Products { get; set; }
        public virtual StatusesRequestsWriteOff StatusesRequestsWriteOff { get; set; }
    }
}
