//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadovDiploma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusesRequestsWriteOff
    {
        public StatusesRequestsWriteOff()
        {
            this.RequestsWriteOff = new HashSet<RequestsWriteOff>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<RequestsWriteOff> RequestsWriteOff { get; set; }
    }
}
